"""Build the publishable copy of the app, and optionally push it.

The repository you develop in and the repository you publish are different things.
This one carries `LOG.md`, the browser suite's screenshots, and a per-feature commit
history -- the log explains the app's own development from the inside, the
screenshots are whatever library the test run happened to have, and the history
contains the log's contents in every revision that touched it. None of that belongs
on a public page, and the last point is why the export starts a **fresh history**
rather than filtering one: a filtered branch would still carry the text.

So publishing is an export with a stated exclusion list. What is *not* excluded is
everything the app is: the code, the tests, the docs, the sample passage in
`corpus/`, and the screenshots the README uses in `assets/`.

    python tools/publish.py                 # build the export, do not push
    python tools/publish.py --push          # build, then push it

The target defaults to ``../diglota`` and keeps its ``.git`` between runs, so the
first push sets ``origin`` and later ones are a single command. Nothing here touches
the development repository: it reads its tracked file list and copies.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Files that exist in the development repository and must not be published.
EXCLUDE = {"LOG.md"}

DEFAULT_TARGET = ROOT.parent / "diglota"
DEFAULT_REMOTE = "https://github.com/<you>/diglota.git"


def git(*args: str, cwd: Path = ROOT, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(("git", *args), cwd=cwd, check=check,
                          capture_output=True, text=True)


def tracked_files() -> list[str]:
    """Everything git tracks here -- which is the point: the reader's own data
    (their deck, their library, their keys) is ignored, so it cannot be exported
    by accident even if this script is wrong about something else."""
    out = git("ls-files").stdout.splitlines()
    return [name for name in out if name not in EXCLUDE]


def copy_one(source: Path, destination: Path) -> None:
    """Copy a file, waiting a moment if Windows says it is in use.

    Running the app *from the export* -- which is exactly what you do to check a
    release -- leaves a process holding the files it imported. Windows then refuses
    the overwrite with a sharing violation, which looks like a bug in this script and
    is really "something is still reading that file". Three tries, then a message
    that says which file and what to do about it.
    """
    for attempt in range(3):
        try:
            shutil.copy2(source, destination)
            return
        except PermissionError:
            if attempt == 2:
                raise SystemExit(
                    f"cannot write {destination}: another process is using it. "
                    "Stop the app if it is running from the export, then run this again."
                )
            time.sleep(0.7)


def copy_out(target: Path) -> int:
    files = tracked_files()
    for name in files:
        destination = target / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        copy_one(ROOT / name, destination)

    # Remove anything the export no longer has. Never `.git`, which holds the
    # remote this was pushed to last time.
    keep = set(files)
    for path in target.rglob("*"):
        if ".git" in path.parts or not path.is_file():
            continue
        if path.relative_to(target).as_posix() not in keep:
            path.unlink()
    return len(files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", type=Path, default=DEFAULT_TARGET)
    parser.add_argument("--remote", default="", help=f"set origin (e.g. {DEFAULT_REMOTE})")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()

    target: Path = args.target.expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    fresh = not (target / ".git").is_dir()
    if fresh:
        git("init", "-b", "main", cwd=target)

    count = copy_out(target)
    print(f"exported {count} files to {target}")
    print(f"  excluded: {', '.join(sorted(EXCLUDE))}, the ignored paths, and shots/")

    git("add", "-A", cwd=target)
    staged = git("diff", "--cached", "--name-only", cwd=target).stdout.strip()
    if staged or fresh:
        verb = "Initial" if fresh else "Update"
        git("commit", "-q", "-m",
            f"{verb} export of the diglot reader\n\n"
            "Generated by tools/publish.py: the app, its tests, its docs, a sample\n"
            "passage in corpus/, and the screenshots the README uses. The development\n"
            "log and the browser suite's screenshots are deliberately not here.",
            cwd=target)
        print(f"  committed ({len(staged.splitlines())} files changed)")
    else:
        print("  nothing changed since the last export")

    if args.remote:
        git("remote", "remove", "origin", cwd=target, check=False)
        git("remote", "add", "origin", args.remote, cwd=target)
        print(f"  origin set to {args.remote}")

    remote = git("remote", "get-url", "origin", cwd=target, check=False).stdout.strip()
    print(f"  remote: {remote or '(none -- pass --remote, or add one by hand)'}")

    if args.push:
        if not remote:
            print("refusing to push: no remote", file=sys.stderr)
            return 1
        result = git("push", "-u", "origin", "main", cwd=target, check=False)
        sys.stdout.write(result.stdout + result.stderr)
        return result.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
